CREATE OR REPLACE VIEW `nhtsa_traffic_fatalities.all_safetyeq` AS
SELECT `consecutive_number`, NULL AS `nm_helmet`, NULL AS `nm_helmet_name`, NULL AS `nm_light`, NULL AS `nm_light_name`, NULL AS `nm_othpre`, NULL AS `nm_othpre_name`, NULL AS `nm_othpro`, NULL AS `nm_othpro_name`, NULL AS `nm_propad`, NULL AS `nm_propad_name`, NULL AS `nm_refclo`, NULL AS `nm_refclo_name`, `non_motorist_safety_equipment_use`, `non_motorist_safety_equipment_use_name`, `person_number`, `state_name`, `state_number`, `vehicle_number` FROM `bigquery-public-data.nhtsa_traffic_fatalities. safetyeq_2015`
UNION ALL
SELECT `consecutive_number`, NULL AS `nm_helmet`, NULL AS `nm_helmet_name`, NULL AS `nm_light`, NULL AS `nm_light_name`, NULL AS `nm_othpre`, NULL AS `nm_othpre_name`, NULL AS `nm_othpro`, NULL AS `nm_othpro_name`, NULL AS `nm_propad`, NULL AS `nm_propad_name`, NULL AS `nm_refclo`, NULL AS `nm_refclo_name`, `non_motorist_safety_equipment_use`, `non_motorist_safety_equipment_use_name`, `person_number`, `state_name`, `state_number`, `vehicle_number` FROM `bigquery-public-data.nhtsa_traffic_fatalities. safetyeq_2016`
UNION ALL
SELECT `consecutive_number`, `nm_helmet`, `nm_helmet_name`, `nm_light`, `nm_light_name`, `nm_othpre`, `nm_othpre_name`, `nm_othpro`, `nm_othpro_name`, `nm_propad`, `nm_propad_name`, `nm_refclo`, `nm_refclo_name`, NULL AS `non_motorist_safety_equipment_use`, NULL AS `non_motorist_safety_equipment_use_name`, `person_number`, `state_name`, `state_number`, `vehicle_number` FROM `bigquery-public-data.nhtsa_traffic_fatalities. safetyeq_2017`
UNION ALL
SELECT `consecutive_number`, `nm_helmet`, `nm_helmet_name`, `nm_light`, `nm_light_name`, `nm_othpre`, `nm_othpre_name`, `nm_othpro`, `nm_othpro_name`, `nm_propad`, `nm_propad_name`, `nm_refclo`, `nm_refclo_name`, NULL AS `non_motorist_safety_equipment_use`, NULL AS `non_motorist_safety_equipment_use_name`, `person_number`, `state_name`, `state_number`, `vehicle_number` FROM `bigquery-public-data.nhtsa_traffic_fatalities. safetyeq_2018`
UNION ALL
SELECT `consecutive_number`, `nm_helmet`, `nm_helmet_name`, `nm_light`, `nm_light_name`, `nm_othpre`, `nm_othpre_name`, `nm_othpro`, `nm_othpro_name`, `nm_propad`, `nm_propad_name`, `nm_refclo`, `nm_refclo_name`, NULL AS `non_motorist_safety_equipment_use`, NULL AS `non_motorist_safety_equipment_use_name`, `person_number`, `state_name`, `state_number`, `vehicle_number` FROM `bigquery-public-data.nhtsa_traffic_fatalities. safetyeq_2019`
UNION ALL
SELECT `consecutive_number`, `nm_helmet`, `nm_helmet_name`, `nm_light`, `nm_light_name`, `nm_othpre`, `nm_othpre_name`, `nm_othpro`, `nm_othpro_name`, `nm_propad`, `nm_propad_name`, `nm_refclo`, `nm_refclo_name`, NULL AS `non_motorist_safety_equipment_use`, NULL AS `non_motorist_safety_equipment_use_name`, `person_number`, `state_name`, `state_number`, `vehicle_number` FROM `bigquery-public-data.nhtsa_traffic_fatalities. safetyeq_2020`
