CREATE OR REPLACE VIEW `nhtsa_traffic_fatalities.all_cevent` AS
    SELECT `area_of_impact_other_vehicle`, `area_of_impact_other_vehicle_name`, `area_of_impact_this_vehicle`, `area_of_impact_this_vehicle_name`, `consecutive_number`, `event_number`, `sequence_of_events`, `sequence_of_events_name`, `state_name`, `state_number`, `vehicle_number_other_vehicle`, `vehicle_number_other_vehicle_name`, `vehicle_number_this_vehicle` FROM `bigquery-public-data.nhtsa_traffic_fatalities. cevent_2015`
UNION ALL
SELECT `area_of_impact_other_vehicle`, `area_of_impact_other_vehicle_name`, `area_of_impact_this_vehicle`, `area_of_impact_this_vehicle_name`, `consecutive_number`, `event_number`, `sequence_of_events`, `sequence_of_events_name`, `state_name`, `state_number`, `vehicle_number_other_vehicle`, `vehicle_number_other_vehicle_name`, `vehicle_number_this_vehicle` FROM `bigquery-public-data.nhtsa_traffic_fatalities. cevent_2016`
UNION ALL
SELECT `area_of_impact_other_vehicle`, `area_of_impact_other_vehicle_name`, `area_of_impact_this_vehicle`, `area_of_impact_this_vehicle_name`, `consecutive_number`, `event_number`, `sequence_of_events`, `sequence_of_events_name`, `state_name`, `state_number`, `vehicle_number_other_vehicle`, `vehicle_number_other_vehicle_name`, `vehicle_number_this_vehicle` FROM `bigquery-public-data.nhtsa_traffic_fatalities. cevent_2017`
UNION ALL
SELECT `area_of_impact_other_vehicle`, `area_of_impact_other_vehicle_name`, `area_of_impact_this_vehicle`, `area_of_impact_this_vehicle_name`, `consecutive_number`, `event_number`, `sequence_of_events`, `sequence_of_events_name`, `state_name`, `state_number`, `vehicle_number_other_vehicle`, `vehicle_number_other_vehicle_name`, `vehicle_number_this_vehicle` FROM `bigquery-public-data.nhtsa_traffic_fatalities. cevent_2018`
UNION ALL
SELECT `area_of_impact_other_vehicle`, `area_of_impact_other_vehicle_name`, `area_of_impact_this_vehicle`, `area_of_impact_this_vehicle_name`, `consecutive_number`, `event_number`, `sequence_of_events`, `sequence_of_events_name`, `state_name`, `state_number`, `vehicle_number_other_vehicle`, `vehicle_number_other_vehicle_name`, `vehicle_number_this_vehicle` FROM `bigquery-public-data.nhtsa_traffic_fatalities. cevent_2019`
UNION ALL
SELECT `area_of_impact_other_vehicle`, `area_of_impact_other_vehicle_name`, `area_of_impact_this_vehicle`, `area_of_impact_this_vehicle_name`, `consecutive_number`, `event_number`, `sequence_of_events`, `sequence_of_events_name`, `state_name`, `state_number`, `vehicle_number_other_vehicle`, `vehicle_number_other_vehicle_name`, `vehicle_number_this_vehicle` FROM `bigquery-public-data.nhtsa_traffic_fatalities. cevent_2020`
